title: Welcome to Programming Hub
author: Abednego Aginam
email: abednegoaginam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site welcomes programmers from all walks of life. You're welcome to 
  Programming hub

# social links
twitter_username: abednego_aginam # DO NOT include the @ character, or else the build will fail!
github_username:  Abednego-py # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
